# Generated by Django 4.2.9 on 2024-01-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('kkal', models.IntegerField(verbose_name='Ккал')),
                ('proteins', models.IntegerField(verbose_name='Белки')),
                ('fats', models.IntegerField(verbose_name='Жиры')),
                ('carbohydrates', models.IntegerField(verbose_name='Углеводы')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('cooking_time', models.IntegerField(verbose_name='Время пригтовления')),
                ('cooking_path', models.TextField(verbose_name='Описание приготовления')),
                ('img_url', models.CharField(max_length=100, verbose_name='Ссылка картинки')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_weight', models.IntegerField(verbose_name='Вес продукта')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe')),
            ],
        ),
    ]
